coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        # basic
        target: auto #default
        threshold: 0%
        base: auto
  fixes:
    - 'before/::after/' # move path   e.g., "before/path" => "after/path"
    - '::after/' # move root   e.g., "path/" => "after/path/"
    - 'before/::' # reduce root e.g., "before/path/" => "path/"
