version: 2.1

orbs:
  cypress: cypress-io/cypress@3

executors:
  node-executor:
    docker:
      - image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
        environment:
          TERM: xterm

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the project
          command: npm run build
      - run:
          name: Start the server
          command: npm run start &
      - run:
          name: Wait for the server to be ready
          command: npx wait-on --timeout 10000 https://codeit-ci-cd-practice.vercel.app/
      - run:
          name: Run Cypress tests
          command: npx cypress run

workflows:
  version: 2
  build:
    jobs:
      - build
