version: 2.1

orbs:
  cypress: cypress-io/cypress@3

executors:
  node-executor:
    docker:
      - image: cypress/browsers:node-18.20.3-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1
        environment:
          TERM: xterm

jobs:
  cypress-tests:
    executor: node-executor
    steps:
      - checkout # Check out your code
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Build the Project
          command: npm run build
      - run:
          name: Start the Server
          command: npm run start &
      - run:
          name: Wait for Server
          command: npx wait-on http://localhost:3000
      - run:
          name: Run Cypress Tests
          command: npx cypress run

workflows:
  version: 2
  build:
    jobs:
      - cypress-tests
